name: Build and Deploy Github Page
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v1
      -
        name: Build
        run: |
          cd client
          npm run build
      -
        name: Deploy
        if: success()
        uses: crazy-max/ghaction-github-pages@v1
        with:
          target_branch: gh-pages
          build_dir: client/build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
