name: Build and Deploy Github Page
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v1
      -
        name: Build and Deploy
        run: |
          cd client
          npm i
          npm run deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
